import Head from "next/head";
import Navbar from "./navbar";
import Footer from "./footer";
import type { ReactElement } from "react";
import { useUser } from "@clerk/nextjs";

export const Layout = ({ children }: { children: ReactElement }) => {
  return (
    <>
      <Head>
        <title>Freetyme</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main className="flex min-h-screen flex-col  bg-gradient-to-b from-tertiary to-secondary">
        {children}
      </main>
      <Footer />
    </>
  );
};

export default Layout;
